# .github/ISSUE_TEMPLATE/documentation.yml
name: 📚 Documentation Issue
description: Report an issue or suggest an improvement for the documentation.
title: '[DOCS] - Brief description of the documentation issue'
labels: ['documentation', 'needs-review']
assignees: [] # Personalizza o lascia vuoto
body:
    - type: markdown
      attributes:
          value: |
              **Thanks for helping improve our documentation!**
    - type: input
      id: location
      attributes:
          label: Location of the Issue (URL or Section)
          description: Please provide the URL or specific section(s) of the documentation where the issue exists.
          placeholder: "e.g., https://your-project-docs-url.com/page/section or 'Installation section in README.md'"
      validations:
          required: true
    - type: textarea
      id: doc-issue-description
      attributes:
          label: Description of the Issue
          description: What is wrong or missing in the documentation? Please be specific.
          placeholder: "e.g., 'The command shown is incorrect', 'This section is unclear', 'Information about X is missing'"
      validations:
          required: true
    - type: textarea
      id: suggested-improvement
      attributes:
          label: Suggested Improvement (Optional)
          description: |
              How could the documentation be improved? If you have specific text changes, please provide them using diff format if possible.
              ```diff
              - Old Text
              + New Text
              ```
          render: diff
      validations:
          required: false
    - type: textarea
      id: additional-info-docs
      attributes:
          label: Additional Information (Optional)
          description: Add any other context, screenshots, or links relevant to the documentation issue here.
      validations:
          required: false
